import type { LayerId } from "./types";

export interface LayerMeta {
  id: LayerId;
  label: string;
  short: string;
  icon: string;
  color: string; // css var hex used for HUD chips
  source: string;
  info: string; // hover blurb / fun fact shown in the Data Layers panel
  defaultOn: boolean;
  // scene-level toggles (e.g. the 3D basemap) aren't data feeds — they have no
  // contact count, so the panel shows ON/— instead of a number.
  noCount?: boolean;
  // optional category the layer belongs to (e.g. "GROUND"). The layer panel
  // prints a small header when the group changes — echoes deltasweep's grouping.
  group?: string;
  // optional second-level header inside a group's dropdown (e.g. INFRA splits
  // into ENERGY / CIVILIAN, like deltasweep). Only used by LayerCategories.
  subgroup?: string;
  // kept in the registry (so the LayerId + render/poll machinery stay intact)
  // but NOT shown in the category menu, so it can never be enabled.
  hidden?: boolean;
}

// Central registry — the HUD, the boot sequence and the renderers all read this.
export const LAYERS: LayerMeta[] = [
  {
    id: "flights",
    label: "LIVE FLIGHTS",
    short: "ACFT",
    icon: "✈",
    color: "#ff2d95",
    source: "ADS-B NETWORK",
    group: "AIR",
    info: "At any given moment roughly 8,000–20,000 aircraft are airborne worldwide — and more than 100,000 flights take off every single day.",
    defaultOn: false,
  },
  {
    // NAVAL / AIS — hidden from the SEA menu (the free AIS relay was unreliable).
    // Kept in the registry so layers.ships stays a real boolean for the renderer.
    id: "ships",
    label: "NAVAL / AIS",
    short: "AIS",
    icon: "⚓",
    color: "#00e5ff",
    source: "AIS RELAY",
    group: "SEA",
    info: "Over 50,000 large merchant ships are at sea right now, carrying around 90% of everything the world trades.",
    defaultOn: false,
    hidden: true,
  },
  {
    id: "navyShips",
    label: "NAVY SHIPS",
    short: "NAVY",
    icon: "⚓",
    color: "#5dff9e",
    source: "CURATED · USN",
    group: "SEA",
    info: "Curated positions of notable military vessels (carriers, destroyers, amphibs) with class, role and embarked-aircraft data from public sources (USN / Naval Vessel Register). Positions are approximate / last-reported, not live AIS — navies don't broadcast.",
    defaultOn: false,
  },
  // BATHYMETRY is live in prod (Esri Ocean imagery, public). SHIPPING ROUTES is
  // still gated to LOCAL/DEV only via NEXT_PUBLIC_SEA_EXTRAS (set in .env.local,
  // NOT in Vercel). Flip it on later by adding that env var in Vercel.
  {
    id: "bathymetry",
    label: "BATHYMETRY",
    short: "DEPTH",
    icon: "≋",
    color: "#4aa3ff",
    source: "ESRI OCEAN",
    group: "SEA",
    info: "Ocean-floor depth (bathymetry) with depth contours from Esri's World Ocean Base — shelves, trenches and ridges beneath the surface.",
    defaultOn: false,
    noCount: true,
  },
  ...((process.env.NEXT_PUBLIC_SEA_EXTRAS
    ? [
        {
          id: "shippingRoutes",
          label: "SHIPPING ROUTES",
          short: "ROUTES",
          icon: "≈",
          color: "#00e5ff",
          source: "WORLD BANK / IMF",
          group: "SEA",
          info: "Global shipping traffic density (World Bank / IMF AIS, 2015–2021) — brighter lanes carry more traffic. A static density map, not live vessel positions.",
          defaultOn: false,
          noCount: true,
        },
      ]
    : []) as LayerMeta[]),
  {
    id: "satellites",
    label: "SATELLITES",
    short: "SATS",
    icon: "🛰",
    color: "#b14bff",
    source: "CELESTRAK · LEO+GEO",
    group: "AIR",
    info: "LEO · Low Earth Orbit (under 2,000 km): the crowded zone where Starlink, the ISS and imaging sats lap the planet about every 90 minutes. GEO · Geostationary (~35,786 km): parked over the equator at Earth's spin speed, so each one hovers above a single spot — TV, weather and comms.",
    defaultOn: false,
  },
  {
    id: "wevents",
    label: "Events",
    short: "EVT",
    icon: "★",
    color: "#ff414e",
    source: "CURATED · OSINT",
    group: "WORLD EVENTS",
    info: "Significant recent intel and kinetic events — strikes, naval incidents, escalations — plotted at the location with severity, confidence, actors and a source link. Curated from current reporting (rolling ~2 months); not a live social scrape.",
    defaultOn: false,
  },
  {
    id: "conflicts",
    label: "World Conflicts",
    short: "WAR",
    icon: "⚔",
    color: "#ff7a3c",
    source: "CURATED · OSINT",
    group: "WORLD EVENTS",
    info: "Every major ongoing armed conflict worldwide — interstate wars, civil wars and insurgencies — with parties, start year and intensity. A curated conflict overview; for live event data use the Events layer.",
    defaultOn: false,
  },
  {
    id: "hormuz",
    label: "Strait of Hormuz",
    short: "SOH",
    icon: "⚓",
    color: "#ffb347",
    source: "LIVE AIS + OSINT",
    group: "WORLD EVENTS",
    info: "Strait of Hormuz live-crossings dashboard — vessel traffic (live AIS), a blockade/chokepoint zone, maritime incidents, and oil-supply vulnerability by country. Opens a filter panel; ~20% of global oil & LNG transits here.",
    defaultOn: false,
    noCount: true,
  },
  {
    id: "events",
    label: "Global News",
    short: "NEWS",
    icon: "⚑",
    color: "#ffe14d",
    source: "GDELT · GLOBAL NEWS",
    group: "WORLD EVENTS",
    info: "GDELT scans the world's news in 100+ languages and refreshes every 15 minutes. This layer clusters the day's conflict, unrest and disaster coverage by the country of the reporting outlets — the brighter the node, the more the world is reporting from there right now. Click a node for the latest headlines.",
    defaultOn: false,
  },
  {
    id: "photoreal",
    label: "PHOTOREAL 3D",
    short: "3D",
    icon: "⬢",
    color: "#5dff9e",
    source: "GOOGLE 3D TILES",
    group: "3D VIEW",
    info: "Google Photorealistic 3D Tiles — a fully textured 3D mesh of the real world (buildings, terrain, bridges), streamed from Google Maps Platform via Cesium ion. Switches the synthwave globe for true Google-Earth-style detail: zoom into any city and tilt to fly between the buildings. Streaming is metered against your ion quota.",
    defaultOn: false,
    noCount: true,
  },
  // ---- GROUND group (deltasweep-style) — kept LAST so its header cleanly
  // separates it and no ungrouped layer trails underneath it ----
  {
    id: "earthquakes",
    label: "SEISMIC",
    short: "SEIS",
    icon: "◉",
    color: "#ffb347",
    source: "USGS FEED",
    info: "About 500,000 earthquakes are detected around the world each year — roughly 100,000 are felt, and around 100 cause damage.",
    defaultOn: false,
    group: "GROUND",
  },
  {
    id: "bases",
    label: "MILITARY BASES",
    short: "BASE",
    icon: "★",
    color: "#ff5a4d",
    source: "OPENSTREETMAP",
    info: "Named military installations across the Middle East and Asia, sourced from OpenStreetMap. Tinted by branch — ground (red), naval (cyan), air (violet).",
    defaultOn: false,
    group: "GROUND",
  },
  {
    id: "strikes",
    label: "Strikes",
    short: "STRK",
    icon: "✸",
    color: "#ff414e",
    source: "CURATED · OSINT",
    info: "Latest reported military strikes across the Iran / Israel / US / Gulf theatre — airstrikes, missile and drone attacks — plotted at the impact location with a source link. Rolling window: only events from roughly the last two months are shown. Curated from current reporting (Al Jazeera and others).",
    defaultOn: false,
    group: "GROUND",
  },
  {
    id: "fires",
    label: "ACTIVE FIRES",
    short: "FIRE",
    icon: "🔥",
    color: "#ff7a3c",
    source: "NASA FIRMS · VIIRS",
    info: "Near-real-time active fires and thermal anomalies detected from orbit by the VIIRS instrument (Suomi-NPP), refreshed by NASA FIRMS several times a day. Each dot is a ~375 m hotspot from the last 24 hours; brighter/redder means higher fire radiative power.",
    defaultOn: false,
    group: "GROUND",
  },
  // ---- INFRA group (deltasweep parity) — ENERGY then CIVILIAN sub-headers.
  // Order here drives the dropdown order, so keep it matching deltasweep. ----
  {
    id: "lng",
    label: "LNG Terminals",
    short: "LNG",
    icon: "⬗",
    color: "#ff5ea8",
    source: "OPENSTREETMAP",
    group: "INFRA",
    subgroup: "ENERGY",
    info: "Liquefied-natural-gas import/export terminals — the coastal plants that chill gas to −162 °C for shipping or regasify it back. Strategic chokepoints in the global energy trade.",
    defaultOn: false,
  },
  {
    id: "nuclear",
    label: "Nuclear Sites",
    short: "NUKE",
    icon: "☢",
    color: "#ff414e",
    source: "CURATED · OSINT",
    group: "INFRA",
    subgroup: "ENERGY",
    info: "Nuclear facilities — power reactors, research reactors, enrichment and fuel-cycle sites, including undeclared/suspected weapons programs. Curated from public OSINT (IAEA, FAS, NTI, Wikipedia).",
    defaultOn: false,
  },
  {
    id: "oilgas",
    label: "Oil & Gas Fields",
    short: "O&G",
    icon: "⬢",
    color: "#ffb347",
    source: "OPENSTREETMAP",
    group: "INFRA",
    subgroup: "ENERGY",
    info: "Producing oil and gas fields and major extraction sites — where hydrocarbons come out of the ground. The upstream end of the energy supply chain.",
    defaultOn: false,
  },
  {
    id: "pipelines",
    label: "Pipelines",
    short: "PIPE",
    icon: "≣",
    color: "#ff8c42",
    source: "GLOBAL ENERGY MONITOR",
    group: "INFRA",
    subgroup: "ENERGY",
    info: "Major oil and gas transmission pipelines — the arteries that move hydrocarbons across borders. Drawn as routes, colored by status.",
    defaultOn: false,
  },
  {
    id: "refineries",
    label: "Refineries",
    short: "REFN",
    icon: "▰",
    color: "#ffd23c",
    source: "OPENSTREETMAP",
    group: "INFRA",
    subgroup: "ENERGY",
    info: "Oil refineries — the plants that turn crude into fuels and petrochemicals. Capacity is measured in barrels per day; the largest exceed a million.",
    defaultOn: false,
  },
  {
    id: "airports",
    label: "Airports",
    short: "AIR",
    icon: "✈",
    color: "#00e5ff",
    source: "OURAIRPORTS",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Major airports worldwide — every large hub plus scheduled-service regional fields. Source: OurAirports (public domain).",
    defaultOn: false,
  },
  {
    id: "minerals",
    label: "Critical Minerals",
    short: "MIN",
    icon: "◆",
    color: "#e25bff",
    source: "USGS / OSM",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Mines and deposits of critical minerals — lithium, rare earths, cobalt, copper and more. The raw materials behind batteries, magnets and the energy transition.",
    defaultOn: false,
  },
  {
    id: "datacenters",
    label: "Data Centers",
    short: "DC",
    icon: "▦",
    color: "#b14bff",
    source: "OPENSTREETMAP",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Data centers — the warehouses of servers that run the cloud, AI and the internet. Clustered around cheap power, cool climates and network hubs.",
    defaultOn: false,
  },
  {
    id: "desal",
    label: "Desalination Plants",
    short: "DSAL",
    icon: "≈",
    color: "#36d2c4",
    source: "OPENSTREETMAP",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Desalination plants — facilities turning seawater into freshwater, a lifeline across the arid Gulf, North Africa and beyond. Energy-hungry and growing fast.",
    defaultOn: false,
  },
  {
    id: "gdp",
    label: "GDP per Capita",
    short: "GDP",
    icon: "$",
    color: "#5dff9e",
    source: "WORLD BANK",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Economic output per person, by country — a choropleth shaded from poorest to richest. World Bank / Natural Earth data.",
    defaultOn: false,
  },
  {
    id: "ports",
    label: "Ports",
    short: "PORT",
    icon: "⚓",
    color: "#4aa3ff",
    source: "NGA WPI",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Major seaports and harbors — the nodes where ~90% of world trade crosses between sea and land. Source: NGA World Port Index (public domain).",
    defaultOn: false,
  },
  {
    id: "cables",
    label: "Submarine Cables",
    short: "CBL",
    icon: "〜",
    color: "#00d2ff",
    source: "TELEGEOGRAPHY",
    group: "INFRA",
    subgroup: "CIVILIAN",
    info: "Submarine communications cables — the fiber-optic lines on the seabed that carry ~99% of intercontinental internet traffic. Drawn as routes between landing points.",
    defaultOn: false,
  },
  // ---- ENVIRO group (deltasweep parity) ----
  {
    id: "waterstress",
    label: "Water Stress",
    short: "H2O",
    icon: "💧",
    color: "#ff7a3c",
    source: "WRI AQUEDUCT 4.0",
    group: "ENVIRO",
    info: "Baseline water risk by river basin (WRI Aqueduct 4.0, HydroSHEDS L6) — shaded from low to extremely high. Click a basin for its risk score.",
    defaultOn: false,
  },
  {
    id: "majorrivers",
    label: "Major Rivers",
    short: "RIV",
    icon: "≈",
    color: "#4aa3ff",
    source: "NATURAL EARTH",
    group: "ENVIRO",
    info: "The world's major rivers and canals (Natural Earth, public domain). Click a river for its name.",
    defaultOn: false,
  },
  {
    id: "landcover",
    label: "Land Cover",
    short: "LULC",
    icon: "◧",
    color: "#5dff9e",
    source: "NASA GIBS · MODIS",
    group: "ENVIRO",
    info: "Global land cover — forest, shrubland, savanna, grassland, cropland, urban, wetland, barren, snow/ice and water — from NASA's MODIS IGBP classification (annual). A raster overlay with a class legend.",
    defaultOn: false,
    noCount: true,
  },
];

export const LAYER_BY_ID: Record<LayerId, LayerMeta> = Object.fromEntries(
  LAYERS.map((l) => [l.id, l])
) as Record<LayerId, LayerMeta>;
